### ISSUE TITLE
Not showing anything (Go 1.5, Vim 7.4)

### ISSUE THREAD

**Issue by casertap** [t-yuki/vim-go-coverlay#2]
the <Leader>c run the test for the current file showing 
vim-go: [test] PASS
but the coverlay do not color any line.
Here is my config 
````
Plugin 'fatih/vim-go'                                   
Plugin 't-yuki/vim-go-coverlay'                         
"config                                                 
au FileType go nmap <leader>c <Plug>(go-coverlay)       
au FileType go nmap <leader>C <Plug>(go-clearlay)       
au BufWritePost *.go call go#coverlay#Coverlay()        
                                                        
````

**Comment by casertap** [comment]
Actually, it works.
I do not know why it was not working right away but I did nothing special and it started to work.
Great plugin, Thanks.

**Comment by svanharmelen** [comment]
@t-yuki I seem to have this same issue... Installed and configured, but don't see any overlays. I'm using NeoVim, is that known to work or should I use the `neovim` branch to get it to work in NeoVim?

I did a quick test with the `neovim` branch, but got an error about trailing characters when trying to call: `go#coverlay#Coverlay(1, )`

Would be great if you can help me get a working setup so I can check out this plugin to see if it will help me with focussing more on testing my code well :wink:

Thanks!
